# Generated by Django 6.0.2 on 2026-02-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
